# Week 1 - Pandas Data Cleaning
Working with the Combined Dataset to practice basic pandas operations.

In [76]:
import pandas as pd

In [77]:
df = pd.read_csv("Combined_dataset.csv")
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

## Step 1: Explore the Data

In [78]:
#First 8 rows
df.head(8)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,NaN,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",NaN,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
6,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399,65.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets

In [79]:
# Last 3 rows
df.tail(3)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [80]:
# Data types
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

## Step 2: Handle Missing Values

In [81]:
# Check missing values per column
missing = df.isnull().sum()
missing[missing > 0]

discount               121
what_customers_said    573
seller_name            301
videos                 781
seller_information     301
variations             562
dtype: int64

In [82]:
print(f"Total missing values: {df.isnull().sum().sum()}")

Total missing values: 2639

In [83]:
# Fill 'discount' (numeric) missing values with 0 (means no discount was given)
df['discount'] = df['discount'].fillna(0)

In [84]:
# Verify no missing values left
print(f"Missing values now: {df.isnull().sum().sum()}")

Missing values now: 2518

## Step 3: Basic Operations (Filter Rows, Select Columns)

In [85]:
# Filter: keep only products with rating >= 1.0
before = len(df)
df = df[df['rating'] >= 1.0]
print(f"Filtered rating >= 1.0: {before} -> {len(df)} rows")

Filtered rating >= 1.0: 1000 -> 886 rows

In [86]:
# Filter: keep only products with price > 0
before = len(df)
df = df[df['initial_price'] > 0]
print(f"Filtered initial_price > 0: {before} -> {len(df)} rows")

Filtered initial_price > 0: 886 -> 886 rows

In [87]:
# Select only the important columns
selected_cols = ['product_id', 'title', 'product_description', 'rating',
                 'ratings_count', 'initial_price', 'discount', 'currency', 'category']
df = df[selected_cols]
print(f"Selected {len(selected_cols)} columns")
df.head()

Selected 9 columns

,product_id,title,product_description,rating,ratings_count,initial_price,discount,currency,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,INR,backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,INR,backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,INR,backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,INR,backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,INR,bath-robe

## Step 4: Remove Duplicates

In [88]:
print(f"Duplicate rows: {df.duplicated().sum()}")

Duplicate rows: 0

### That is , no need to remove duplicates

## Step 5: Create Derived Columns

In [89]:
# Derived Column 1: discount_amount (actual rupee savings)
df['discount_amount'] = df['initial_price'] * (df['discount'] / 100)

# Derived Column 2: value_score (composite of rating & popularity)
df['value_score'] = df['rating'] * df['ratings_count']

print(f"Added 2 derived columns. Total columns now: {len(df.columns)}")
print(f"Columns: {list(df.columns)}")
df[['title', 'initial_price', 'discount', 'discount_amount', 'rating', 'ratings_count', 'value_score']].head(10)

Added 2 derived columns. Total columns now: 11
Columns: ['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'currency', 'category', 'discount_amount', 'value_score']

,title,initial_price,discount,discount_amount,rating,ratings_count,value_score
0,Lino Perros,3995,58.0,2317.10,3.8,15,57.0
1,Tommy Hilfiger,2899,35.0,1014.65,4.5,67,301.5
2,Lavie,2999,65.0,1949.35,4.4,226,994.4
3,F Gear,1675,52.0,871.00,4.4,1052,4628.8
4,MYTRIDENT,2899,17.0,492.83,4.7,12,56.4
5,H&M,1399,0.0,0.00,4.5,42,189.0
6,AVI Living,1399,65.0,909.35,4.0,5,20.0
7,My Room,2999,54.0,1619.46,4.7,10,47.0
8,My Room,2999,54.0,1619.46,4.5,22,99.0
9,Story@home,2199,53.0,1165.47,3.7,7,25.9

## Step 6: Save Cleaned Dataset

In [93]:
df.to_csv("Cleaned_dataset.csv", index=False)
print(f"Saved 'Cleaned_dataset.csv'")
print(f"Final shape: {df.shape}")
print(f"Columns: {list(df.columns)}")

Saved 'Cleaned_dataset.csv'
Final shape: (886, 11)
Columns: ['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'currency', 'category', 'discount_amount', 'value_score']

In [94]:
# Quick look at the final cleaned data
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,currency,category,discount_amount,value_score
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,INR,backpacks,2317.10,57.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,INR,backpacks,1014.65,301.5
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,INR,backpacks,1949.35,994.4
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,INR,backpacks,871.00,4628.8
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,INR,bath-robe,492.83,56.4